// <auto-generated />
namespace lyq.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update20181103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update20181103));
        
        string IMigrationMetadata.Id
        {
            get { return "201811031244490_update20181103"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
